### ISSUE TITLE
Recyclerview row & column problem

### ISSUE THREAD

**Issue by ozankonur** [kingfisherphuoc/EasyRecyclerViewIndicator#6]
I have a recyclerview that has 2 rows and 3 columns.. When I use this indicator, it is displaying circles as adapter items size. But I want to display only 1 circle indicator for 6 items... 

Is it possible ? any suggetion ?

**Comment by kingfisherphuoc** [comment]
@ozankonur you can try to use `AnyViewIndicator`. In this case, you have to calculate the position yourself. Here's the tip:

```
anyViewIndicator.setItemCount(yourItemSize/6 + 1); // set the total count of  indicator
anyViewIndicator.setCurrentPosition(0); // set the current position of indicator
// Display the current position of indicator when recyclerview scrolls.
recyclerView2.addOnScrollListener(new RecyclerView.OnScrollListener() {
    @Override
    public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
        super.onScrollStateChanged(recyclerView, newState);
        switch (newState) {
            case RecyclerView.SCROLL_STATE_IDLE:
                int findFirstCompletelyVisibleItemPosition = ((LinearLayoutManager) recyclerView.getLayoutManager()).findFirstCompletelyVisibleItemPosition();
                anyViewIndicator.setCurrentPosition(findFirstCompletelyVisibleItemPosition/6+1);
                break;
        }
    }
});
```

**Comment by ozankonur** [comment]
oh okay I will try it, I was started to change library method parameters like ` public void setRecyclerView(final RecyclerView recyclerView,int RecyclerViewRowNumber,int RecyclerViewColumnNumber) `

**Comment by ozankonur** [comment]
Hi @kingfisherphuoc 

I am trying anyViewIndicator but I am getting null and I dont know maybe this because on this method you are trying to cast LinearLayoutManager but I have GridLayoutManager in my recyclerview;

`    @Override
    protected int getCurrentPosition() {
        return ((LinearLayoutManager) recyclerView.getLayoutManager()).findFirstCompletelyVisibleItemPosition();
    }`

What do you think ?

**Comment by ozankonur** [comment]
@kingfisherphuoc  I think I have to set RecyclerView to anyViewIndicator, right ?

**Comment by ozankonur** [comment]
@kingfisherphuoc  Thank you it is working good!
